name: Test Release

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VULNCHECK_API_KEY: ${{ secrets.VULNCHECK_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Generate NVD Feeds
        run: |
          mkdir ./vulndb
          touch ./vulndb/"$(date)"
          sleep 1
          touch ./vulndb/"$(date)"
            
      - name: Current date
        id: date
        run: |
          echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      # - name: Tag
      #   run: |
      #     git config --global user.email ""
      #     git config --global user.name "GitHub Actions Bot"
      #     git pull
      #     git commit --allow-empty -m 'Release ${{ steps.date.outputs.date }}'
      #     git push origin main
          
      - name: Release
        run: |
          gh release create ${{ github.ref_name }} \
            --notes "Automated release ${{ github.ref_name }} \
            --title "cve-${{ steps.date.outputs.date }}"
            --generate-notes

      - name: Upload Release Assets
        run: |
          for file in ./vulndb/*; do
            gh release upload ${{ github.ref_name }} "$file" --clobber
          done

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          delete_tag_pattern: ^cve-.*
          keep_latest: 144
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
